apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeploy822
  labels:
    app: autodeploy822
    kubernetes.azure.com/generator: devhub
  namespace: namespace-workflow-1717384009500
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeploy822
  template:
    metadata:
      labels:
        app: autodeploy822
    spec:
      containers:
        - name: autodeploy822
          image: AKScluster822registry.azurecr.io/image-workflow-1717384009500:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
