apiVersion: v1
kind: Service
metadata:
  name: autodeploy822
  namespace: namespace-workflow-1717384009500
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: autodeploy822
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000